### PR TITLE
Add Fixturify for generating apps for testing purpose

### PR DESCRIPTION
**Pull request by suchitadoshi1987**

### CODE REVIEW

**Comment by scalvert** [comment]
Thanks for adding this! I'd like to do a few things before we merge this:

1. Explore using `ember-cli`'s version of this by importing from that package (this is private, so could be subject to breakage). We may not need the extra functionality it provides, but I'd like to at least explore that before doing more work.
2. Add at least one test that uses `fixurify-project` end-to-end, so others who are contributing can use that as an example. `ember-cli` should have some reasonable examples.

**Comment by rwjblue** [comment]
👍 - fixturify-project is definitely great for our testing needs

**Comment by scalvert** [comment]
Well, we _do_ want to test in-repo addons and engines, so having creating those out of the box would be nice.

**Comment by suchitadoshi1987** [comment]
On it!

**Comment by suchitadoshi1987** [comment]
Closing in favor of https://github.com/scalvert/ember-cli-checkup/pull/22

**Pull request closed without merging**
